import header from './header'
import plist from './plist'
import mlist from './mlist'
import demsg from './detail/msg'
import defol from './detail/follow'
import deals from './detail/deal'
import toast from './tool/toast'
import alert from './tool/alert'
import more from './tool/more'
export default { header, plist, mlist, demsg, defol, deals, toast, alert, more }
